island:
  world: "Acid Island"

  size: 128
  spacing: 8

  origin:
    x: 500
    z: 500

  y: 100

  template:
    file: "starter.yml"
    max_blocks: 32768

  spawn:
    x: 0
    y: 4
    z: 0

storage:
  islands_file: "islands.json"

acid:
  enabled: true

  world_only: true
  water_level: 50

  damage:
    enabled: true
    interval: 20

    effect:
      type: "poison"
      duration: 2
      amplifier: 0
      hide_particles: true